stages:
  - build
  - tag
  - deploy
  - notify
################## BUILD ####################
Build internal:
  stage: build
  variables:
    SERVICE_NAME: UserProfile internal
  only:
    - develop
  script: |
    echo "set-up ci/cd for project"
    gcloud builds submit  --config=cloudbuild.yaml --substitutions=_JOB_NAME=${CI_PROJECT_NAME},_IMAGE_TAG=${IMAGE_TAG}

#################DEPLOY################
Deploy Staging QC:
  stage: deploy
  when: manual
  variables:
    SERVICE_NAME: UserProfile internal
  only:
    - develop
  script: |
    echo "deploy service on staging enviroment"

