// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: intern.proto

package intern

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtraUserInfoReq_Status int32

const (
	ExtraUserInfoReq_NONE    ExtraUserInfoReq_Status = 0
	ExtraUserInfoReq_STARTED ExtraUserInfoReq_Status = 1
	ExtraUserInfoReq_ENDED   ExtraUserInfoReq_Status = 2
)

// Enum value maps for ExtraUserInfoReq_Status.
var (
	ExtraUserInfoReq_Status_name = map[int32]string{
		0: "NONE",
		1: "STARTED",
		2: "ENDED",
	}
	ExtraUserInfoReq_Status_value = map[string]int32{
		"NONE":    0,
		"STARTED": 1,
		"ENDED":   2,
	}
)

func (x ExtraUserInfoReq_Status) Enum() *ExtraUserInfoReq_Status {
	p := new(ExtraUserInfoReq_Status)
	*p = x
	return p
}

func (x ExtraUserInfoReq_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtraUserInfoReq_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_intern_proto_enumTypes[0].Descriptor()
}

func (ExtraUserInfoReq_Status) Type() protoreflect.EnumType {
	return &file_intern_proto_enumTypes[0]
}

func (x ExtraUserInfoReq_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtraUserInfoReq_Status.Descriptor instead.
func (ExtraUserInfoReq_Status) EnumDescriptor() ([]byte, []int) {
	return file_intern_proto_rawDescGZIP(), []int{0, 0}
}

type ExtraUserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hobbies string `protobuf:"bytes,1,opt,name=Hobbies,proto3" json:"Hobbies,omitempty"`
}

func (x *ExtraUserInfoReq) Reset() {
	*x = ExtraUserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_intern_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtraUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraUserInfoReq) ProtoMessage() {}

func (x *ExtraUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_intern_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraUserInfoReq.ProtoReflect.Descriptor instead.
func (*ExtraUserInfoReq) Descriptor() ([]byte, []int) {
	return file_intern_proto_rawDescGZIP(), []int{0}
}

func (x *ExtraUserInfoReq) GetHobbies() string {
	if x != nil {
		return x.Hobbies
	}
	return ""
}

type ExtraUserInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExtraUserInfoRes) Reset() {
	*x = ExtraUserInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_intern_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtraUserInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraUserInfoRes) ProtoMessage() {}

func (x *ExtraUserInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_intern_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraUserInfoRes.ProtoReflect.Descriptor instead.
func (*ExtraUserInfoRes) Descriptor() ([]byte, []int) {
	return file_intern_proto_rawDescGZIP(), []int{1}
}

var File_intern_proto protoreflect.FileDescriptor

var file_intern_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x22, 0x58, 0x0a, 0x10, 0x45, 0x78, 0x74, 0x72, 0x61, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x6f,
	0x62, 0x62, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x48, 0x6f, 0x62,
	0x62, 0x69, 0x65, 0x73, 0x22, 0x2a, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08,
	0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x52,
	0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4e, 0x44, 0x45, 0x44, 0x10, 0x02,
	0x22, 0x12, 0x0a, 0x10, 0x45, 0x78, 0x74, 0x72, 0x61, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x32, 0x4d, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x78,
	0x74, 0x72, 0x61, 0x12, 0x3e, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x2e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_intern_proto_rawDescOnce sync.Once
	file_intern_proto_rawDescData = file_intern_proto_rawDesc
)

func file_intern_proto_rawDescGZIP() []byte {
	file_intern_proto_rawDescOnce.Do(func() {
		file_intern_proto_rawDescData = protoimpl.X.CompressGZIP(file_intern_proto_rawDescData)
	})
	return file_intern_proto_rawDescData
}

var file_intern_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_intern_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_intern_proto_goTypes = []interface{}{
	(ExtraUserInfoReq_Status)(0), // 0: intern.ExtraUserInfoReq.Status
	(*ExtraUserInfoReq)(nil),     // 1: intern.ExtraUserInfoReq
	(*ExtraUserInfoRes)(nil),     // 2: intern.ExtraUserInfoRes
}
var file_intern_proto_depIdxs = []int32{
	1, // 0: intern.UpdateExtra.Update:input_type -> intern.ExtraUserInfoReq
	2, // 1: intern.UpdateExtra.Update:output_type -> intern.ExtraUserInfoRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_intern_proto_init() }
func file_intern_proto_init() {
	if File_intern_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_intern_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtraUserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_intern_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtraUserInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_intern_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_intern_proto_goTypes,
		DependencyIndexes: file_intern_proto_depIdxs,
		EnumInfos:         file_intern_proto_enumTypes,
		MessageInfos:      file_intern_proto_msgTypes,
	}.Build()
	File_intern_proto = out.File
	file_intern_proto_rawDesc = nil
	file_intern_proto_goTypes = nil
	file_intern_proto_depIdxs = nil
}
